---
functional:
  - Решение задачи на скорость против другого игрока.
  - Оба игрока видят друг у друга редактор с кодом
  - Игроки видят вывод тестов
  - Можно менять язык программирования во время решения 
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузера Google Chrome
  - Сайт должен быть протестирован на совместимость с последними версиями браузера Mozilla Firefox
  - Сайт должен быть протестирован на совместимость с последними версиями браузера Яндекс Браузер
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен иметь форму регистрации пользователя
  - Сайт должен иметь форму входа зарегистрированного пользователя
  - Почта указанная при регистрации должна быть валидной
  - Можно создать новую задачу
  - Можно просмотреть задачи
  - Можно создать новый турнир
  - Можно просмотреть информацию о турнирах
  - Можно войти, используя учетную запись GitHub
  - Можно войти, используя учетную запись Discord  # нет учетной записи Discord
  - Можно играть используя язык C++.
  - Можно играть используя язык Golang.
  - Можно играть используя язык Java.
  - Можно играть используя язык Python.
  - Можно играть используя язык Ruby.
  - Можно играть используя язык PHP.
  - Можно играть используя язык Node.js.
