---
functional:
  - Решение задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - требование 2
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - требование 4
implicit:
  - Сайт должен иметь форму регистрации пользователя
  - Сайт должен иметь форму входа зарегистрированного пользователя
  - Почта указанная при регистрации должна быть валидной
  - требование 6

Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
Сайт должен быть безопасным и защищать данные пользователя
Сайт должен быть удобным на мобильном устройстве
Сайт должен быть протестирован на совместимость с последними версиями браузеров
Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

Решение задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
Можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
Задачи даны на двух языках — русском и английском
Другие пользователи могут следить за ходом игры
В игре есть чат, в котором общаются зарегистрированные пользователи
Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время

---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь форму регистрации пользователя
  - Сайт должен иметь форму входа зарегистрированного пользователя
  - Сайт должен иметь русскую и английскую версии
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре на русском языке
  - Сайт должен быть SPA-приложение, которое не перезагружает страницу
  - При оформлении заказа пользователь должен указать контактные данные
  - При оформлении заказа должен произойти переход на страницу оплаты
  - Корзина должна храниться в сессии браузера
  - При выборе языка рядом с английским языком должно отображаться изображение флага англоязычной страны
  - Должна быть возможность сбросить фильтр по категории
  - При нажатии на фильтр по Категориям товаров должны отображаться все категории
  - В таблице списка товаров в корзине должны быть заголовки
  - В таблице списка товаров в корзине столбец, показывающий колличество товаров, должен быть выровнен
  - В таблице списка товаров в корзине рядом с артикулами товаров не должно быть слов "шт." и "qty."
